version: '3.8'

services:
  #  db:
  #    image: postgres:15-alpine
  #    container_name: farma_db
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    environment:
  #      - POSTGRES_USER=${POSTGRES_USER}
  #      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #      - POSTGRES_DB=${POSTGRES_DB}
  #    ports:
  #      - "5432:5432"
  #    networks:
  #      - farma_net

  backend:
    build: ./backend
    container_name: farma_backend
    volumes:
      - ./backend:/app
    ports:
      - "8321:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    networks:
      - farma_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: farma_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5178:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - farma_net

networks:
  farma_net:
    driver: bridge
